apiVersion: v2
name: control-layer
description: A Helm subchart for deploying the Doubleword control layer component
type: application
version: 0.2.0
appVersion: 0.7.0
annotations:
  org.opencontainers.image.source: https://github.com/doublewordai/control-layer-chart
  org.opencontainers.image.description: Helm chart for deploying the Doubleword control layer service
  org.opencontainers.image.licenses: Apache-2.0
