{{- $external := .Values.keystore.external | default dict -}}
{{- if and .Values.keystore.enabled (not ($external.enabled | default false)) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "control-layer.fullname" . }}-keystore
  labels:
    {{- include "control-layer.keystore.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "control-layer.keystore.selectorLabels" . | nindent 4 }}
{{- end }}
