apiVersion: v1
kind: Secret
metadata:
  name: {{ include "control-layer.fullname" . }}-postgres-secret
  labels:
    {{- include "control-layer.postgres.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.secrets.postgres.data }}
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
