{{- if .Values.secrets.controlLayer.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "control-layer.fullname" . }}-secret
  labels:
    {{- include "control-layer.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.secrets.controlLayer.data }}
  {{- range $key, $value := . }}
  {{- if and (eq $key "DATABASE_URL") (empty $value) $.Values.postgresql.enabled }}
  {{ $key }}: "postgres://{{ $.Values.secrets.postgres.data.POSTGRES_USER }}:{{ $.Values.secrets.postgres.data.POSTGRES_PASSWORD }}@{{ $.Release.Name }}-postgres:5432/{{ $.Values.secrets.postgres.data.POSTGRES_DB }}"
  {{- else if $value }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
