apiVersion: v1
kind: Secret
metadata:
  name: {{ include "control-layer.fullname" . }}-secret
  labels:
    {{- include "control-layer.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- $secrets := .Values.secrets.controlLayer.data }}
{{- $pg := .Values.secrets.postgres.data }}
{{- $generatedDbUrl := printf "postgres://%s:%s@%s-postgres:5432/%s" $pg.POSTGRES_USER $pg.POSTGRES_PASSWORD .Release.Name $pg.POSTGRES_DB }}

{{- $dbUrl := (coalesce $secrets.DATABASE_URL "") }}
{{- if and (empty $dbUrl) .Values.postgresql.enabled }}
  {{- $dbUrl = $generatedDbUrl }}
{{- end }}

{{- range $key, $value := $secrets }}
{{- if ne $key "DATABASE_URL" }}
{{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}

DATABASE_URL: {{ $dbUrl | quote }}

